# Just runs docs from docs/test, simulates mvn setup
name: Docs only build

on:
  push:
    branches: [ "docs/test" ]

env:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_TESTSHADES_OPTS: "-f testShades/pom.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # -Dmaven.repo.local=.m2/repository not needed on github, seems ~/.m2 is supported / expected
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Building site against Spark321
          # bare bones for site setup
          script: |
            echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -P Spark321) > version.txt
      - uses: ./.github/workflows/mkdocs
        with:
          # save the previous version coverage and mvn site
          copyFromScript: |
            version=$(cat version.txt)
            mkdir site_safety_box
            if [ ! -f "$version/coverage.txt" ]; then
              echo "Using simulated coverage.txt"
              echo 86.30 > site_safety_box/coverage.txt
              echo 76.04 >> site_safety_box/coverage.txt
            else
              echo "Copying coverage"
              cp $version/coverage.txt site_safety_box/
            fi
            cp site_safety_box/coverage.txt .
            if [ -d "$version/site" ]; then
              echo "Copying site"
              cp -rf $version/site site_safety_box/
            else
              echo "Could not find site"
            fi
          # copy back the files
          copyToScript: |
            echo "Copying coverage.txt to docs"
            cp coverage.txt docs/
            if [ -d "site_safety_box/site" ]; then
              echo "Copying site to docs"
              cp -rf site_safety_box/site docs/
            fi
